[[profile]]
name = "monitor"

     [[profile.output]]
     enable = true
     search = ["m=BenQ EX2710R", "v=BNQ"]
     mode = "2560x1440@59.951Hz"
     position = "0,0"
     scale = 1.0
     transform = "normal"
     adaptive_sync = false

     [[profile.output]]
     enable = false
     search = ["m=0x13B0", "s=", "v=Chimei Innolux Corporation"]
     mode = "2560x1600@60.002Hz"
     position = "-1536,480"
     scale = 1.66667
     transform = "normal"

[[profile]]
name = "laptop"

    [[profile.output]]
         enable = true
         search = ["m=0x13B0", "s=", "v=Chimei Innolux Corporation"]
         mode = "2560x1600@60.002Hz"
         position = "0,0"
         scale = 1.66667
         transform = "normal"
         adaptive_sync = false

[[profile]]
name = "dual"

     [[profile.output]]
     enable = true
     search = ["m=BenQ EX2710R", "v=BNQ"]
     mode = "2560x1440@59.951Hz"
     # position = "1536,-480"
     position = "0,0"
     scale = 1.0
     transform = "normal"
     adaptive_sync = false

     [[profile.output]]
     enable = true
     search = ["m=0x13B0", "s=", "v=Chimei Innolux Corporation"]
     mode = "2560x1600@60.002Hz"
     position = "-1536,480"
     scale = 1.66667
     transform = "normal"
     adaptive_sync = false
