#!/usr/bin/env sh

source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

if [[ "$(gsettings get org.gnome.desktop.interface color-scheme)" =~ "dark" ]]; then
  export DARK_MODE=true
  export BAT_THEME=nord-light
else
  export BAT_THEME=nord
fi

export GOPATH="$HOME/.local/share/go"
export PATH="$HOME/.cargo/bin:$PATH"

