bindkey -e

# Remove '/' from wordchars.
WORDCHARS="${WORDCHARS/\//}"

setopt autocd beep extendedglob nomatch notify


HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=100000

setopt hist_ignore_all_dups hist_ignore_space share_history extended_history
setopt hist_expire_dups_first

autoload -U add-zsh-hook

function set-nvim-listen-address {
    local server_name="default"
    if [ "$TMUX" ]; then
        local tmux_window=$(tmux display-message -p '#S-#I' 2> /dev/null)
        server_name="tmux-$tmux_window"
        return
    fi
    local sway_ws=$(swaymsg -t  get_workspaces 2> /dev/null | \
       jq -r "map(select(.focused == true)) | map(.name) | first")
    local i3_ws=$(i3-msg -t  get_workspaces 2> /dev/null | \
       jq -r "map(select(.focused == true)) | map(.name) | first")

    if [ "$sway_ws" ]; then
        server_name="sway-$sway_ws"
    elif [ "$i3_ws" ]; then
        server_name="i3-$i3_ws"
    fi

    # Set the NVIM listen address. Works for the server (launched via `nvim`)
    # and client (launched via `nvr`).
    export NVIM_LISTEN_ADDRESS="/tmp/nvim-${server_name:-$1}.sock"
}
add-zsh-hook chpwd set-nvim-listen-address
set-nvim-listen-address

# Initialize zoxide when available.
if [ -n "${commands[zoxide]}" ]; then
  eval "$(zoxide init zsh)"
fi

# Initialize mise when available.
if [ -n "${commands[mise]}" ]; then
    eval "$(mise activate zsh)"
fi

alias btm='btm --battery'

PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.cargo/bin
